# Generated by Django 3.2.9 on 2021-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('gold', models.IntegerField()),
                ('water', models.IntegerField()),
                ('ferilize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('date', models.TextField()),
                ('pumpGetTime', models.TextField()),
                ('fertilizeGetTimes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EcologyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('weedsNum', models.IntegerField()),
                ('offlineTime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IrrIgationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('waterNum', models.IntegerField()),
                ('lastWaterSpownTime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('watchedArticlesId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('fieldID', models.TextField()),
                ('plantngTime', models.TextField()),
                ('currentWaterngCount', models.IntegerField()),
                ('currentFerilizeCount', models.IntegerField()),
                ('lastWaterTime', models.TextField()),
                ('lastFerilizeTine', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('fieldID', models.TextField()),
                ('plantingTime', models.TextField()),
                ('harvestTime', models.TextField()),
                ('reward', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('date', models.TextField()),
                ('topicAndOptions', models.TextField()),
                ('choose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phoneNum', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('avatarSprte', models.TextField()),
                ('signUpDate', models.TextField()),
            ],
        ),
    ]
